apiVersion: v1
kind: Service
metadata:
  name: vllm-gptoss
  namespace: gptoss
spec:
  selector:
    app: vllm-gptoss
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
