apiVersion: v1
kind: Service
metadata:
  name: scout
  namespace: vllm
spec:
  selector:
    app: scout
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32328   # Exposed NodePort (external port)
  type: NodePort
