apiVersion: v1
kind: Service
metadata:
  name: llama
  namespace: vllm
spec:
  selector:
    app: llama
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32328
  type: NodePort
